/*
Okteto Public API

Testing ApplicationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okteto

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okteto-community/sleep-namespaces/sleeper/okteto"
)

func Test_okteto_ApplicationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApplicationsAPIService ListApplicationsForNamespace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespaceName string

		resp, httpRes, err := apiClient.ApplicationsAPI.ListApplicationsForNamespace(context.Background(), namespaceName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
